blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/greggh/nvim/discussions
    about: Please ask and answer questions here.
  - name: Neovim Documentation
    url: https://neovim.io/doc/
    about: Check the official Neovim documentation first
  - name: Neovim FAQ
    url: https://github.com/neovim/neovim/wiki/FAQ
    about: Check if your question is answered in the Neovim FAQ
  - name: Lua Guide for Neovim
    url: https://github.com/nanotee/nvim-lua-guide
    about: Helpful guide for understanding Lua in Neovim contexts