return {
  "folke/which-key.nvim",
  event = { "VeryLazy" },
  opts = {
    preset = "modern",
    delay = vim.o.timeoutlen,
    triggers = {
      { "<auto>", mode = "nixso" },
    },
    plugins = {
      marks = true,
      registers = true,
      spelling = {
        enabled = true,
        suggestions = 20,
      },
      presets = {
        motions = false,
        operators = false,
        text_objects = true,
        windows = true,
        nav = true,
        z = true,
        g = true,
      },
    },
    win = {
      border = "none",
      padding = { 1, 2 },
      wo = { winblend = 0 },
    },
    expand = 1,
    spec = {
      { "<leader>a", group = "AI Tools" },
      { "<leader>b", group = "Buffers" },
      { "<leader>c", group = "Code & Commands" },
      { "<leader>d", group = "Debug" },
      { "<leader>f", group = "Files" },
      { "<leader>g", group = "Git" },
      { "<leader>l", group = "LSP" },
      { "<leader>n", group = "Notifications" },
      { "<leader>o", group = "Options" },
      { "<leader>p", group = "Packages" },
      { "<leader>q", group = "Quit & Save" },
      { "<leader>s", group = "Sessions" },
      { "<leader>t", group = "Tests" },
      { "<leader>u", group = "Misc" },
      { "<leader>w", group = "Windows & Smart Splits" },
      { "<leader>x", group = "Diagnostics" },
      { "<leader>y", group = "Yank" },
    },
  },
}
