name: Test Neovim Configuration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # Optionally add other OS if needed:
        # os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly

      - name: Install dependencies
        run: |
          # Install luarocks
          sudo apt-get update
          sudo apt-get install -y luarocks

          # Install luacheck for linting
          sudo luarocks install luacheck

          # Install stylua for formatting
          # Get the latest version from GitHub
          STYLUA_VERSION=$(curl -s https://api.github.com/repos/JohnnyMorganz/StyLua/releases/latest | grep -oP '"tag_name": "\K[^"]+')
          STYLUA_URL="https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64.zip"
          
          # Download and extract stylua
          curl -L -o stylua.zip $STYLUA_URL
          unzip stylua.zip
          chmod +x stylua
          sudo mv stylua /usr/local/bin/

      - name: Check Neovim version
        run: |
          nvim --version

      - name: Run Linting
        run: |
          # Run luacheck with our config file
          luacheck lua/ tests/ --config=.luacheckrc

      - name: Run Tests
        run: |
          make test