name: Test Neovim Configuration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Neovim ${{ matrix.nvim-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        nvim-version: [stable, nightly]
        # Optionally add other OS if needed:
        # os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-version }}

      - name: Install dependencies
        run: |
          # Install luarocks
          sudo apt-get update
          sudo apt-get install -y luarocks

          # Install luacheck for linting
          sudo luarocks install luacheck

      - name: Install StyLua
        uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          token: ${{ github.token }}

      - name: Check Neovim version
        run: |
          nvim --version

      - name: Run Linting
        run: |
          # Run luacheck with our config file
          luacheck lua/ tests/ --config=.luacheckrc

      - name: Run Tests
        run: |
          make test